### ISSUE TITLE
angular-xeditable doesn't work well within ui-bootstrap <uib-tabset> element

### ISSUE THREAD

**Issue by LegendOfFire** [vitalets/angular-xeditable#594] opened 2016-12-21 01:08 UTC
I embed a angualr-xeditable inside a uib-tabset element, however the form can't be submitted.

Please check the code: http://plnkr.co/edit/itDFMD?p=preview

**Comment by ckosloski** [comment] 2016-12-21 02:00
I think the issue is how uib-tab handles clicks.  Please see #563.  There is a working example there.

**Comment by ckosloski** [comment] 2016-12-22 14:06
Please close this issue if your issue is solved.

**Closed** 2016-12-23 02:25 UTC
