### ISSUE TITLE
editable-select does not work properly with objects

### ISSUE THREAD

**Issue by dlwhiteman** [vitalets/angular-xeditable#238] opened 2015-01-27 04:30 UTC
When an editable-select has a model consisting of primitive objects, such as strings, it works fine.  However, it has difficulty with two way synchronization with JSON objects.  In the following example, I show how you can configure a standard select element to work with an ng-model consisting of objects.  When the select is changed, a different person object is displayed.  Likewise, if I click the Change User button, it will advance to a different person, and the select widget and anchor text are both updated correctly.  However, when you use the editable-select to change the person, it causes two problems. The standard select widget is unable to correctly display the person, and when you attempt to open the editable-select again, the correct person is not-preselected (instead, a blank entry is added to the select).  Here is the JSFiddle that demonstrates the issue: http://jsfiddle.net/dlwhiteman/3x7aLpeh/4/

**Comment by dlwhiteman** [comment] 2015-01-30 21:19
What appears to happen is the editable-select is making copies of the objects that are listed in ng-options, so that even if the ng-model refers to one of the objects in that initial array, it doesn't match an item in the select widget upon initial display.

**Comment by T1mobil3** [comment] 2015-03-06 10:12
+1

**Comment by tarlepp** [comment] 2015-04-14 05:26
+1 Any updates with this?

**Comment by troygilbert** [comment] 2015-05-07 15:45
+1

**Comment by valiantvu** [comment] 2015-06-16 06:59
+1

**Comment by hassanwasef** [comment] 2015-07-02 08:39
+1

**Comment by andremann** [comment] 2015-07-29 10:23
+1

**Comment by smnmtzgr** [comment] 2015-08-13 11:16
+1

**Comment by bubblepixel** [comment] 2016-03-02 16:25
+1

**Comment by beedaan** [comment] 2016-04-11 21:34
+1

**Comment by ckosloski** [comment] 2016-04-11 21:43
I looked at the jsfiddle in the original post and I'm not seeing what the issue is.  Both dropdowns are being updated when I select a value in either dropdown.

**Comment by beedaan** [comment] 2016-04-11 22:10
@ckosloski Thank you for the quick response! It looks like the issue has indeed been resolved. I was experiencing the issue with an older build  (0.1.8).  I confirmed the issue exists with the older build in a fiddle: http://jsfiddle.net/beedaan/evx01emj/1/

It appears this issue is fixed in the latest distribution, so I would close this issue.

**Closed** 2016-04-12 07:52 UTC
