### ISSUE TITLE
Searchable drop down support with the grid

### ISSUE THREAD

**Issue by Sampath-Lokuge** [vitalets/angular-xeditable#436] opened 2016-03-12 17:40 UTC
Hi,

Can I use searchable drop downs with this api ?  I need to use it with the [Editable row](https://vitalets.github.io/angular-xeditable/#editable-row) and [Editable table](https://vitalets.github.io/angular-xeditable/#editable-table).Please let me know about this.Thanks.

**Comment by ckosloski** [comment] 2016-03-16 16:42
Not right now.  You would have to integrate something like [ui-select](https://github.com/angular-ui/ui-select) into the project.

**Comment by Sampath-Lokuge** [comment] 2016-03-16 16:50
@ckosloski Yes,But I have seen there are problems on that integration.Please see the link below.Thanks.

**[ui-select Issues with Xeditable](https://github.com/vitalets/angular-xeditable/pull/300)**

**Comment by ckosloski** [comment] 2016-03-16 20:28
I'm pretty sure the issue is that ui-select requires a model with a "." in it i.e. "model.dropdown".  The model that gets passed to ui-select from xeditable is $data and that is why the example plunkr in the link your provided doesn't work.

Not quite sure how to fix it though.

Here is the link to the ui-select [faq](https://github.com/angular-ui/ui-select/wiki/FAQs) that explains the model behavior.

**Comment by ckosloski** [comment] 2016-03-16 20:40
Actually, I think I have it working.  Please check out this [plunker](http://plnkr.co/edit/uH83T9nAVlB5JaHOxxtx?p=preview) that is a fork of the one you referenced.

**Comment by Sampath-Lokuge** [comment] 2016-03-16 20:43
@ckosloski  Aha.. Thanks a lot for the invaluable information.I'll also try it on coming days and will let you know.Thanks again :+1:

**Comment by eugef** [comment] 2016-04-09 11:59
Fixed by #451

**Closed by eugef** 2016-04-09 11:59 UTC
