### ISSUE TITLE
popover for bsdate

### ISSUE THREAD

**Issue by fborges42** [vitalets/angular-xeditable#711] opened 2017-12-15 12:31 UTC
Hey, I'm trying to open bsdate on a popover but the buttons go off the popover. I have the same popover for text and it works just fine. Any clue if this is a bug or am I missing something here?

**working:**
![image](https://user-images.githubusercontent.com/10809728/34042132-1820042e-e193-11e7-8b2b-eded9aa67bc6.png)

**not working:**
![image](https://user-images.githubusercontent.com/10809728/34042148-2cdcbb64-e193-11e7-9e2d-a0110bad38f8.png)
**html:**
```
<div class="popover-wrapper">
   <a href="#" editable-bsdate="object.Date" e-is-open="opened.$data" e-ng-click="open($event,'$data')" e-datepicker-popup="dd/MM/yyyy" onbeforesave="changeDate($data);" e-bs-datepicker>
      <span>{{object.Date | date:"dd/MM/yyyy"}}</span>
   </a>
</div>
```

Best,
fb

**Comment by ckosloski** [comment] 2017-12-18 21:26
Based on the demo site, the issue is the following css coming from forms.less:
```
@media (min-width: 768px)
forms.less:514
.form-inline .input-group > .form-control {
    width: 100%;
}
```
If you change it to `width:auto`, that appears to fix the issue.
You should probably either create a new style class for this or pass in `e-style="width:auto"` to your editable-bsdate.

**Comment by fborges42** [comment] 2017-12-19 10:22
Thanks for the input @ckosloski this worked!

**Comment by ckosloski** [comment] 2017-12-19 14:28
@fborges42 glad I could help.  If this solves your issue, please close it.

**Closed** 2017-12-19 16:52 UTC
