### ISSUE TITLE
Popover instead of inline

### ISSUE THREAD

**Issue by webchaz** [vitalets/angular-xeditable#210] opened 2014-11-19 20:58 UTC
Is there anyway to use a popover instead of having inline inputs?

**Comment by cadrogui** [comment] 2015-08-26 22:13
here is a good solution, works for me!..

http://ryanlanciaux.github.io/blog/2013/10/16/fake-popovers-for-angular-xeditable/

regards.

**Comment by dbrgn** [comment] 2016-01-08 15:56
Probably a duplicate of #146 and #81.

**Closed** 2016-06-24 09:03 UTC
