### ISSUE TITLE
Inside <form> not working

### ISSUE THREAD

**Issue by sarath2** [vitalets/angular-xeditable#6] opened 2013-09-08 11:46 UTC
Following not working..
```

<form>
   <a href="#" editable-text="user.name">{{ user.name | uppercase }}</a>
</form>

**Comment by phpniki** [comment] 2015-03-01 12:40
+1 bug remain i have a problem with editable row table inside a form please help me

**Comment by ousmaneo** [comment] 2015-03-06 17:18
+1

**Comment by summerrain** [comment] 2015-03-12 02:08
+1

**Comment by mmilito** [comment] 2015-03-12 21:58
I had this problem also ... was able to fix it by explicitly stating <form editable-form=""> 

In jade, the browser translates from this:  
    form editable-form  
to this: 
    <form editable-form="editable-form">

It seems the value of the attribute being set is the problem, so the browser needs to be worked around if it is adding the value if not specifically stated.

Hope this helps.

**Comment by abrapps** [comment] 2015-03-22 05:00
+1

**Comment by kevinspacey** [comment] 2015-03-23 13:02
+1

**Comment by skidvd** [comment] 2015-03-27 15:58
+1

**Comment by Petro-Kashpurenko** [comment] 2015-03-28 17:24
+1

**Comment by olso** [comment] 2015-04-02 02:52
+1

**Comment by tasneem93** [comment] 2015-04-02 12:40
so many people having the same issue but still no updates? 

+1

**Comment by promolic1** [comment] 2015-04-02 16:22
@tasneem93 Well, probably "solving" this is complicated. Maybe it means to change the whole idea of how xeditable works, because is designed to create forms dynamically. And also we can't change how html works to allow forms inside another forms. Not sure if this will be "solved" soon...

**Comment by erossignon** [comment] 2015-04-08 10:20
+1

**Comment by Sylox** [comment] 2015-04-08 18:16
+1

**Comment by r-coursera** [comment] 2015-04-09 18:35
+1

**Comment by Ledragon** [comment] 2015-04-13 14:32
Work around/solution here?
 http://stackoverflow.com/questions/24996429/form-with-editable-elements-should-have-editable-form-attribute
It seems that setting the button type to button make it work (at least worked for me)

**Comment by mabumeshref** [comment] 2015-04-19 14:04
+1

**Comment by baio** [comment] 2015-04-30 12:40
+1

**Comment by rfink** [comment] 2015-05-01 09:53
+1

**Comment by luccascorrea** [comment] 2015-05-01 12:31
+1

**Comment by xmlking** [comment] 2015-05-16 21:54
+1

**Comment by mitcht** [comment] 2015-06-01 20:01
Hopefully this will get merged. Its the simplest thing... just add 'e-single' to any item you want to have ignore the outer form.

**Comment by eugenia-arias** [comment] 2015-06-26 09:23
+1

**Comment by mitcht** [comment] 2015-06-26 12:29
I've spoken one of the previous owners of this project.  It may have been somewhat abandoned / going stale at this point.  Correct me if i'm wrong.

**Comment by innerpeace0** [comment] 2015-06-26 13:53
The founder, vitalets, told me that he is off the project. I got the sense that he doesn't plan on returning any time soon. It would be a good project for somebody to take over. The concept is great.

**Comment by mitcht** [comment] 2015-06-26 13:54
I spoke with painyjames and he was under the assumption that vitalets is currently the project owner. I've sent some emails and we'll see what happens.

**Comment by eugef** [comment] 2015-07-17 07:45
Hi all, project now has new contributor.

Issue is confirmed (here is example of the bug http://jsfiddle.net/NfPcH/9316/) and the patch to fix it #315 would be merged in the nearest time.

**Comment by phaniram** [comment] 2015-07-26 14:06
Any ETA on this merge?

**Comment by mitcht** [comment] 2015-07-27 12:22
Here is the list of things to do.  I'm planning on working on them in my spare time...
https://github.com/vitalets/angular-xeditable/milestones

**Comment by eugef** [comment] 2015-08-05 15:05
Resolved by #315

**Closed** 2015-08-05 15:05 UTC
Labels: bug

**Comment by HariBabuThubati** [comment] 2015-09-01 20:47
@eugef : http://vitalets.github.io/angular-xeditable/#editable-table , here if i click on edit and changing the values , onclick event the new values are not writing into local modal ,but in cast submit button it was writing into the local modal , can you please help me out , i am working on this issue since a week ,could not able to figured out.

**Comment by HariBabuThubati** [comment] 2015-09-01 20:48
http://vitalets.github.io/angular-xeditable/#editable-table , here if i click on edit and changing the values , onclick event the new values are not writing into local modal ,but in cast submit button it was writing into the local modal , can you please help me out , i am working on this issue since a week ,could not able to figured out.

**Comment by HariBabuThubati** [comment] 2015-09-01 20:51
http://vitalets.github.io/angular-xeditable/#editable-table , here if i click on edit and changing the values , onclick event the new values are not writing into local modal ,but in cast submit button it was writing into the local modal , can you please help me out , i am working on this issue since a week ,could not able to figured out.

**Comment by mitcht** [comment] 2015-09-01 20:52
Seriously?

**Comment by HariBabuThubati** [comment] 2015-09-01 21:47
@mitcht  Yes , please advise me

**Comment by christandy** [comment] 2015-12-16 19:45
vitalets - Is there a way to do multiple separate editable forms within a single form element? I've got a large form and would like to break it up a bit. Thanks for any help.

**Comment by HugCoder** [comment] 2016-01-17 11:31
This still seems to be broken. I tried different hacks and "solutions", including the "e-single" which doesn't seem to do anything. There seems to be workarounds here to get somewhere, but what I want to accomplish is the following:
I have a table with cells (<td>) containing content I want to use xeditable on, i.e. I don't want to edit the whole row or the whole table at the same time, since this expands the table too big cause of the inputs taking more space than text. I also don't want buttons, I want save on blur (buttons="no" blur="submit"). I only want the element I click on to be editable. This is fine as long as it's not surrounded by a <form> but when I add it, things start breaking. First of it stops displaying the inputs on click, cause it wants myform.$show() to be called. If it's called it displays all the xeditables, which is what I don't want.

I could just do all validation through onbeforesave="validate($data)" or something like that, but that takes quite a bit of extra code and I would like to use angulars inbuilt features like dirty, pristine, etc., which is only available if you surround everything with <form>. So, is there a solution to achieve the above?

**Comment by dnauck** [comment] 2016-02-04 18:09
Even the latest master branch had this issue :/

+1 for fixing it

**Comment by christandy** [comment] 2016-02-04 18:44
What's worked for me is to just nest form elements inside each other. I am well aware that that approach is non-standard, won't validate, and could fairly be called "hackish".

**Comment by mitcht** [comment] 2016-02-04 19:18
Just because my commit  has been merged does not mean that it has been built into the bower distribution as of the date of this comment. Anyone who knows how this stuff works would know that they can clone the repo, build it locally and use the results from that build on their site. This will make e-single work.  If you find yourself bower-installing xeditable and then going "hey e-single isn't working" you need to do your own build on your own machine. Learn this. Contribute. It will take you to the next level.

**Comment by HugCoder** [comment] 2016-02-15 11:17
I implemented the e-single fix by simply changing the lines:
`// element wrapped by form
                if (ctrl[1]) {
                    eFormCtrl = ctrl[1];
                    hasForm = true;
                    }`
to
`// element wrapped by form
                if (ctrl[1]) {
                    eFormCtrl = ctrl[1];
                    if (attrs.eSingle !== undefined) {
                        hasForm = false;
                    } else {
                        hasForm = true;
                    }`
Makes it work inside forms without any problem so far.

**Comment by mitcht** [comment] 2016-02-16 03:11
You could always ask to be a repo admin :)

**Comment by mitcht** [comment] 2016-02-16 15:16
Submitted build as pull req. Fingers crossed.

https://github.com/vitalets/angular-xeditable/pull/422

**Comment by mitcht** [comment] 2016-02-17 13:34
https://github.com/vitalets/angular-xeditable/pull/422 merged

bower install angular-xeditable now allows e-single with version 0.1.10

**Comment by HugCoder** [comment] 2016-02-19 13:44
Sounds good, but to me it doesn't seem to be implemented in the way we have "fixed" it in the thread. Now it's like this:
"
         if(ctrl[1]) {
           eFormCtrl = ctrl[1];
          hasForm = true;
        } else if(attrs.eForm) { // element not wrapped by form, but we have e-form attr
          hasForm = attrs.eSingle === undefined;
        }
"
This means we still cannot wrap the element in <form> but instead we have to use only e-form. Then we don't get the angular form validation etc. that the form tag provides. I really don't see what problem this implementation solved. At least it didn't solve the original issue discussed in this thread.

**Comment by mitcht** [comment] 2016-02-20 17:05
It allows xeditable elements to be used with a standard ng-form element.  You can then create your own form, and the elements themselves don't have to validate using the internal e-form validation.  Just make sure they have names, and they will show up on your ng-form scope object with validity booleans.  This allows you to do things like implement angular-message without having to come up with ways to sidestep the built in validation in xeditable.

**Comment by im1dermike** [comment] 2016-02-22 18:11
What a joke that this hasn't been fixed.  It makes the plugin completely unusable.

**Comment by mitcht** [comment] 2016-02-22 18:17
@HugCoder do you have an open pull req? There doesn't seem to be one.  If you create a pull req, i'll merge it.

@im1dermike 
#1, i don't see a pull request from you fixing this.  #2, angular-xeditable is free, so if you don't like it go somewhere else.  #3, There ARE ways to deal with this.  For instance you aren't forced to use the validation schemes.  I prefer angular-message. I don't bother trying to make angular-xedtiable handle all form stuff, even though it can, but doesn't do it quite as you would expect.

**Comment by mohamednagy** [comment] 2016-06-28 11:56
i have a form and i want to edit the only clicked editable controller not all the editable controllers in the form.

**Comment by bgsavage** [comment] 2017-01-04 23:23
@mitcht can you provide a code sample of how to use your fix?  It sounds like you're saying we should try using ng-form instead of the built in e-form now.

Thanks-

**Comment by doctore** [comment] 2017-01-21 12:13
I have a similar problem, that is, I have an "outer form" that manages other elements and I would like to include an "editable table" like this:

https://vitalets.github.io/angular-xeditable/#editable-row

But I haven't achieved. I have searched similar use cases I have found a lot of "closed issue" related with it:

https://github.com/vitalets/angular-xeditable/issues/6
https://github.com/vitalets/angular-xeditable/issues/138
https://github.com/vitalets/angular-xeditable/issues/421
...

I really don't understand how you can close issues without solve them. Is it a joke?
If the component compels you to include a form to manage an "inner table" (or other similar use cases), is it so difficult to imagine that another form already exists in the "original HTML"?

**Comment by thejohnfreeman** [comment] 2017-01-21 15:55
Maybe check out [ag-grid](https://www.ag-grid.com/javascript-grid-cell-editing/) if you want editable cells in a table.
