### ISSUE TITLE
Required field validation is not working

### ISSUE THREAD

**Issue by altaf-sami** [vitalets/angular-xeditable#76] opened 2014-01-22 17:00 UTC
See the fiddle.

http://jsfiddle.net/NfPcH/93/

First row name is required, but it is not working, Please help.

Thanks.

**Comment by robertscholz** [comment] 2015-02-16 12:23
The problem is that the `e-form="rowform"` attribute is not transfered from the `span` element to the `input` element in edit mode. All other attributes prefixed with `e-*` are transfered but not `e-form`. So the resulting input element becomes:
```html
<input type="text" name="name" required="required" class="editable-input form-control ng-pristine ng-valid ng-valid-required" ng-model="$data">
```
instead of:
```html
<input type="text" name="name" form="rowform" required="required" class="editable-input form-control ng-pristine ng-valid ng-valid-required" ng-model="$data">
```
Without the `form` attribute on the input element html5 validation attributes such as `required`, `min` and `max` will not work. If the `form` attribute was transfered correctly to the input element we only have to update the `form` element in the JSFiddle to have the `id` attribute set to the value that is used in the `form` attribute on the `input` element. So (from the JSFiddle) the form element:
```html
<form editable-form name="rowform" onbeforesave="saveUser($data, user.id)..."
```
should be:
```html
<form editable-form name="rowform" id="rowform" onbeforesave="saveUser($data, user.id)..."
```
The code for omitting the `form` attribute seems intentionally when looking at the source code:
```javascript
// exclude `form` and `ng-submit`, 
if(transferAttr === 'Form' || transferAttr === 'NgSubmit') {
    continue;
}
```

**Comment by Sylox** [comment] 2015-04-03 12:34
any update on this?

**Comment by phpniki** [comment] 2015-04-18 12:34
+1 any update?

**Comment by pnowy** [comment] 2015-05-25 19:43
+1 any update?

**Comment by marthinal** [comment] 2015-06-11 08:44
Hi guys I fixed the problem checking form errors.

I have created a pull request and here is the patch

https://github.com/marthinal/angular-xeditable/commit/d983f03d6be4d05a586ceded6b5e693cff7ba341

**Comment by marthinal** [comment] 2015-06-11 10:28
If you are adding css styles when validating and you need to remove it once the form is submitted, then you need to set $submitted to false. Please read:

http://www.codedisqus.com/CHVjeXgWgg/angularjs-form-gets-pristine-but-still-submitted.html

**Comment by mitcht** [comment] 2015-07-27 13:27
The question is, why are you guys putting a <form> tag inside of a repeater?  Try to eliminate this, and i bet your problem will go away.  I use tons of fields on pages with validation on each one of them.  I only use one form.  If it comes to where I have a directive with xeditable items inside it, and that directive is used more than one time on the page (like your 'rows' in the example), i make sure that each e-name has a unique identifier on it.  You can't have a bunch of forms with a bunch of elements that have the same name and expect validation to work right.

**Comment by celsomtrindade** [comment] 2015-07-28 11:47
@mitcht i understand what you said, and also already tried this. But, at least for me, when i use the form outside of the repeater, everything inside that form with be active for editing when i click on the edit icon of a row, and not just a single row. Any idea why?

**Comment by mitcht** [comment] 2015-07-28 12:26
I believe its working exactly as it was intended.  According to the documents...


If you need validation of individual editable elements then you should define onbeforesave on particular editable element.
The **result of child's onbeforesave is important for next step**:
string: submit will be cancelled, form will stay opened, string will be shown as error message
not string: submit will be continued

This leads me to think that your checkname function needs to perform the validation routines.  see my jsfiddle here.  
https://jsfiddle.net/carcomp/64oc7wdp/

This would mean that any field you add 'onbeforesave' to will have to be manually validated for all circumstances, not just a single check on a specific row.   

As for your question about the whole thing being editable, well, its because its inside a form.  I was seeing the same results.  Just look into how i set up the js in my fiddle and go from there.

**Comment by celsomtrindade** [comment] 2015-07-28 12:32
Yes, until that part i understood. But for example, i need to validate a field based on a mask, but i'm not able to do so. I even posted a [question on stackoverflow](http://stackoverflow.com/questions/31542958/angularjs-x-editable-table-row-validation), but until now, i didn't got any answer.

I can validate, like your example, but only if it match a certain 'name' or if it's not blank.
Do you have any idea why?

**Comment by mitcht** [comment] 2015-07-28 12:35
What sort of validation do you want?  I mean, its a text box. You either have data, or you don't have data.

**Comment by celsomtrindade** [comment] 2015-07-28 12:44
But for example, i have a telephone field, so it need to have a especific type of data. I mean, it's not necessary to validate it based on the mask itself, it could be based on the input being `$invalid`. But even with this I'm not able to validate, because the input field doesn't get the proper `ng-model` name i set. It's always like: `ng-model="$data"` no matter what i set on the `e-ng-model` attr.

**Comment by mitcht** [comment] 2015-07-28 14:58
You know what? I just don't think it makes sense to try to attempt form validation with multiple form tags.  I have tried multiple ways to make this work, and the fact is that ng-repeat creates isolate scope for each form.  This invariably denies any global validation to happen.  Its not specifically a problem with xeditable.. It just the concept of putting forms with inputs in an AngularJS repeater is somewhat flawed, even if there is a demo showing to do it in the docs.  

If you want this to work, you are going to have to write a custom directive and manually manipulate the isolate scope of each form into the 'main' form that is for the entire page. 

I cannot stress enough that it is not xeditable causing this.  Its AngularJS + multiple form tags + isolate scope.

**Comment by thiagohac** [comment] 2015-10-16 17:50
+1 any update?

e-required do not work.

**Comment by mitcht** [comment] 2015-10-16 17:52
Its not been merged yet.

**Comment by mitcht** [comment] 2015-10-16 17:59
Ok everyone, look into using the $validators to add a custom validation you want.  The more you learn about angularJs, the more you can unlock.

for instance, here is an example

Your view would (should) be like this
<span custom-date-time editable-text="user.name" ng-model="blargh"  e-name="name" e-form="rowform" required>

That should cause the below attibute validators to fire off..  Makes it so you can ONLY type in a valid date, nothing else. Also forces the ng-model to be a datetime no matter what is typed.

'use strict';

angular.module('myAppName')
  .directive('customDateTime', ['$moment', function ($moment) {
    return {
      restrict: 'A',
      require: '?ngModel',
      link: function(scope, element, attrs, ngModel) {
        if (!ngModel) { return; }
  
        ngModel.$validators.date = function (value) {
          return value instanceof Date === true;
        };        

        ngModel.$parsers.unshift(function(value) {
          var datePicked = null;
          
          // Attempt to use JS built in date and validate
          var tmpDate = new Date(value);
          if ($moment(tmpDate).isValid()){
            // If you typed in the time, this will convert it to something we can store
            datePicked = tmpDate;
          } 
          
          return datePicked;
        });
      }
    };
  }]);

**Comment by Sampath-Lokuge** [comment] 2016-01-13 19:10
Is there any permanent solution for this ? I mean it should work with the `e-required`

**Comment by beedaan** [comment] 2016-04-12 21:05
@mitcht I agree and what you posted will work.  I found this thread because I was looking for general documentation for the `e-required` directive and couldn't find anything.  There are only three mentions of it on the project homepage and none address it directly.  The main question that I would like to have answered is *should I be using it if it's available?*

**Comment by claudionunezjr** [comment] 2016-06-01 21:46
Seriously need to remove e-required from the docs and demos (doesn't even work in the demos) if a working example cannot be presented. How much more frustrating can this get. At least, the docs should have some note about this.

**Comment by ckosloski** [comment] 2016-06-02 01:57
The `e-required` example does work in the document [here](http://vitalets.github.io/angular-xeditable/#text-customize).  It uses the HTML5 required validation.  Are you using a browser that supports HTML5 validation?  I know that Safari does not support it.

**Comment by claudionunezjr** [comment] 2016-06-21 20:37
Thanks for your response. Unfortunately, that example (http://vitalets.github.io/angular-xeditable/#text-customize) doesn't demonstrate the table scenario. The issue is with the ng-repeat(ing) of the table rows and maintaining scope appropriately. I did have to hook in my own validation. Maybe there is no "real" native solution for this without having to build in additional logic to address this. Just would be nice if this exact scenario (using e-require with tables - repeating rows) would indicate this limitation in that section of the docs.

**Comment by ckosloski** [comment] 2016-06-22 13:20
`e-required` does not work in the `editable-form` case because the form is submitted via a script.  HTML5 validation only runs if a form is submitted via the submit button.

I will add a note to the documentation about this fact.

**Comment by buzai** [comment] 2016-11-08 10:04
@ckosloski E-required not work, then I can only onbeforesave () method to check the parameters of the? But I used a lot of e-required before, and the use of onbeforesave very troublesome. Is there a simple solution? .

**Comment by ckosloski** [comment] 2016-11-08 14:52
e-required does work in some situations.  How are you trying to use it?
If you are checking for existence of a value, I think onbeforesave is the only other option.

**Comment by buzai** [comment] 2016-11-09 03:17
@ckosloski ,In a  form ,I want check input  value before click save button

**Comment by ckosloski** [comment] 2016-11-09 12:39
You have to use onbeforesave to check input values before saving.  Or maybe have an onchange on the input field that can validate the input.

**Comment by buzai** [comment] 2016-11-10 02:10
@ckosloski thanks ,now i am know

**Comment by eugef** [comment] 2017-01-07 15:01
@ckosloski is there anything we can improve in the code, or issue can be closed?

**Comment by ckosloski** [comment] 2017-01-07 15:29
Everything is working as intended, which isn't what some people are looking for.  No one has offered a pull request to improve the functionality so I suggest closing it.

**Closed** 2017-01-07 19:06 UTC
Labels: bug
