### ISSUE TITLE
$activate(name) not working

### ISSUE THREAD

**Issue by beedaan** [vitalets/angular-xeditable#459] opened 2016-04-18 19:41 UTC
I am trying to set the focus on a specific field with the `$activate(name)` method.  I am invoking the method in my template using the `ng-click` directive.
```html
ng-click="rowform.$activate('programId')"
```
I put a log statement in the `$activate(name)` method to see if it was being called.  It looks like it's being called, but the parameter is not properly being passed.  Instead, the value is undefined.
```javascript
$activate: function(name) {
   console.log('activate field', name);
   ...
}
```
`activate field undefined`

**Comment by ckosloski** [comment] 2016-04-18 19:44
Can you create a plunker showing this issue?

**Comment by beedaan** [comment] 2016-04-18 20:29
I updated the jsfiddle from the docs for the editable form:
http://jsfiddle.net/beedaan/wvrqm1xb/

In the fiddle, I tried to set the focus to the status column.  I called `$activate` from the template and from the controller.  I couldn't get either to work.  It would be greatly appreciated if someone could show me how to use the `activate(name)` method to set the focus on the status in the example.

**Comment by ckosloski** [comment] 2016-04-18 20:46
Are you trying to set it on edit or add?

**Comment by beedaan** [comment] 2016-04-18 20:47
I'm trying to set it on add.

**Comment by ckosloski** [comment] 2016-04-19 20:50
The reason you are seeing "activate field undefined" is because be default, the activate function is called by the show method with an empty name value.  This then sets the active field to the first entry field by default.

This also means that wherever you are setting calling $activate is not being called.

The problem is that when you click the add button, there is no form object yet, so you can't call activate on it yet.

One option is to set ` onshow="setFocus(rowform, user)"` on the form object.
In the add method, you set an "added" flag to true.

The setFocus method checks for the added flag and does a settimeout to wait for the form to finish rendering.
```javascript
  $scope.setFocus = function(rowform, user) {
    if (user.added) {
      $timeout(function () {
        user.added = false;
        rowform.$activate('status');
      }, 50);
    }
  };
```

**Comment by beedaan** [comment] 2016-04-28 20:38
Very interesting!  I'm in the middle of creating a `setFocus()` method to activate the field I'd like to.  My trouble is stemming from the list of editables being created in an order that is different from order of appearance on the page.  I have an `editable-number` element first in my editables array, even though it's the third element.  Two editable-selects are before it.  I need to understand how the editables array is created so I can better predict which field will have focus once the form is $shown.

**Comment by beedaan** [comment] 2016-04-29 14:33
I propose this issue is closed because we know that `$activate()` is indeed working.  I will say that I think the documentation is lacking regarding the behavior of this method.

**Comment by ckosloski** [comment] 2016-04-29 14:44
What do you think needs to be added to the documentation?

**Comment by beedaan** [comment] 2016-04-29 16:03
I think it would be worth mentioning that you cannot activate a form field
if you are adding a row because the form is not available yet.  You have to
use the $timeout module and give the form a chance to be created, then
activate the field.

**Comment by ckosloski** [comment] 2016-05-03 21:21
@beedaan you should be able to close this issue yourself.

I will add something in the documentation in my next pull request.

**Closed** 2016-05-04 11:36 UTC
