### ISSUE TITLE
Control deselects when navigating outside the area

### ISSUE THREAD

**Issue by bartdk-be** [vitalets/angular-xeditable#757] opened 2019-09-12 06:56 UTC
A lot of users complain about the fact that the control switches from "editable" to "readonly" when they click inside > move mouse outside > and release the mouse.
- Click inside (ex : if you want to select the text and copy paste the information)
- Move mouse outside control
- Release mouse
--> You are no longer able to copy paste that information

https://github.com/vitalets/angular-xeditable/blob/ca6d768a74f341df2ab6fe498a09fde24ec66926/src/js/editable-form/controller.js#L43

We fixed the issue on our local version by changing the OnClick to a MouseDown.
If we create a pull request for this topic, any chance it can be merged into the main version ?

**Comment by drsmog** [comment] 2019-09-26 12:16
pls review records - https://www.loom.com/share/2b01f81d1bca49c380a3727bf2147f2a

brief context:
problem: when you are doing mouse up outside on input box, submit is triggering.
reason: because we r listening on click event - line: 1485 - `$document.bind('click', function (e) { ....`
solution: listen to mousedown like - `$document.bind('mousedown', function (e) {`

**Comment by drsmog** [comment] 2019-09-26 12:19
@ckosloski pls take a look and update if that change is ok - sorry for that urgency but we are in a hurry and it cause some usability issue for our customers

**Comment by ckosloski** [comment] 2019-09-26 12:52
What kind of configuration are you using for xeditable?
If I go here - http://vitalets.github.io/angular-xeditable/#text-simple
I can't reproduce the issue
You are welcome to create a pull request.

**Comment by drsmog** [comment] 2019-09-26 13:09
@ckosloski  thanks for such a quick response. I was able to reproduce same on that link pls take a look - https://www.loom.com/share/5ccd44b7e58d4babbbecd8fea3a17b85

ok thats great ill push a PR

**Comment by drsmog** [comment] 2019-09-26 13:22
@ckosloski i've made a PR - https://github.com/vitalets/angular-xeditable/pull/758 . pls take a look once u will have some time for that.
thanks a lot 👍

**Comment by ckosloski** [comment] 2019-09-26 13:31
So I was able to reproduce this in chrome, but it works correctly in firefox.

**Comment by ckosloski** [comment] 2019-10-29 15:03
Please close this.

**Closed** 2019-10-29 15:44 UTC
