### ISSUE TITLE
Able to use popover style of x-editable?

### ISSUE THREAD

**Issue by k-funk** [vitalets/angular-xeditable#146] opened 2014-07-08 00:14 UTC
http://vitalets.github.io/x-editable/demo-bs3.html
As in this example, there's two modes to using x-editable. Inline and popover/popup.

1: Are these possible with angular-xeditable?
2: Can they be decided in the html, on the element, per element, instead of globally?

**Comment by nikhil-bhandari** [comment] 2015-02-11 12:27
+1

**Comment by Assada** [comment] 2015-03-12 15:45
+1

**Comment by petrabarus** [comment] 2015-03-24 03:04
+1

**Comment by gerzhan** [comment] 2015-03-27 02:41
+1

**Comment by cadrogui** [comment] 2015-04-03 16:31
+1

**Comment by Nishchit14** [comment] 2015-05-02 06:21
+1 Please give this ASAP :+1:

**Comment by t-k-** [comment] 2015-11-02 05:56
+1

**Comment by itzik-ilan** [comment] 2015-11-02 15:47
+1

**Comment by igor-smyrnov** [comment] 2015-12-30 05:30
+1

**Comment by dbrgn** [comment] 2016-01-08 15:55
I think this is a duplicate of #81.

**Comment by ckosloski** [comment] 2017-01-02 20:46
@eugef I think this can be closed due to #491

**Closed** 2017-01-03 22:24 UTC
