### ISSUE TITLE
there is something wrong in your jsfiddle

### ISSUE THREAD

**Issue by gerome0123** [vitalets/angular-xeditable#650] opened 2017-04-24 08:16 UTC
![screen shot 2017-04-24 at 4 16 07 pm](https://cloud.githubusercontent.com/assets/20182366/25328133/4d66e24e-2909-11e7-87f9-aa35eba9d0f3.png)

**Comment by ckosloski** [comment] 2017-04-24 13:41
This is a duplicate of #647, please close.
Also, I just checked in a change fixing the fiddle links, a new build is required.

**Closed** 2017-04-25 01:04 UTC
